import * as THREE from "three";

export const fishConfig = {
  radius: 0.3,
  length: 0.8,
  highlightedScale: 1,
  visualScale: 1,
  radialSegments: 36,
  heightSegments: 3,
  highlightedIndex: 0,
  bodyColor: new THREE.Color(0xf2f6ff),
  highlightedColor: new THREE.Color(0xf2f6ff),
  renderBoundsRadius: 17,
  arrowLength: 0.52,
  arrowRadius: 0.16,
  arrowRadialSegments: 9,
  arrowHeightSegments: 4,
  ribbonLength: 3.25,
  ribbonHeadWidth: 0.16,
  ribbonTailWidth: 0.012,
  ribbonSegments: 36,
  ribbonWaveAmplitude: 0.28,
  ribbonTaperPower: 1.95,
  ribbonOpacity: 0.46,
  ribbonCurveMax: 2.35,
  swimFrequencyMin: 1.4,
  swimFrequencyMax: 3.2,
  maxBankAngle: THREE.MathUtils.degToRad(12),
  bankTurnScale: 0.18,
  bankResponse: 8,
  curveDeformationStrength: 0.72,
  curveDeformationMax: 2.35,
  curveDeformationResponse: 12,
  swimCurveStrength: 0.92,
  swimAccelerationThreshold: 0.35,
  swimAccelerationFull: 2.4,
  swimAccelerationPulseSeconds: 0.32,
  swimTurnCurveStart: 0.08,
};
